### ISSUE TITLE
"exception": "Non-static method VXM\\Async\\Async::run() should not be called statically",

### ISSUE THREAD

**Issue by valh1996** [vuongxuongminh/laravel-async#10]
Hello,

Whatever I do, your example gives me an error :

`"exception": "Non-static method VXM\\Async\\Async::run() should not be called statically"`

Here is my code based on your example :
```php
public function index(Request $request)
{
    Async::run(function () {
        // Can I use a new instance of Laravel here?
        return 123;
    }, [
        'success' => function ($output) { 
            \Log::debug($output);
        },
        'timeout' => function () { 
            \Log::debug('timeout');
        },
        'error' => function (\Throwable $exception) {
            \Log::debug($exception->getMessage());
        },
    ]);
}
```

Do you have any idea please ? 

Is it possible to use all the functions of Laravel in the child process please?

PS : Is it also possible to keep the child process open while the parent process has not been completed? 

Thank you
Val'

**Comment by vuongxuongminh** [comment]
Hi, Make sure you are using `Async` facade not call direct to `VXM\Async\Async`. Yes, you can call all functions of Laravel in child process.

**Comment by valh1996** [comment]
Thanks!
So I can use all the functions of Laravel inside the child process, but we agree that it is not shared with the parent process? I have a singleton that I would like to "duplicate" (not the same user id) in the child process to make it communicate with the one in the parent process. I don't know if it's clear

**Comment by vuongxuongminh** [comment]
Task should be PSR-4 named, can you rename and try again?
