### ISSUE TITLE
The serialized output may only be 10240 bytes long :(

### ISSUE THREAD

**Issue by gmarsano** [vuongxuongminh/laravel-async#16]
Hello!

Thanks for this awesome package.

It would be really nice if a configuration was implemented for the Spatie Async Pool@add $outputLength argument. Then:

```php
public function run($job, array $events = []): self
{
    $process = $this->createProcess($this->makeJob($job));
    $process->then($this->makeProcessListener('success', $process));
    $process->catch($this->makeProcessListener('error', $process));
    $process->timeout($this->makeProcessListener('timeout', $process));
    $this->addProcessListeners($events, $process);
    $this->pool->add($process);

    return $this;
}
```

Can look something like this:
```php
$this->pool->add($process, $outputLengthFromConfig);
```

**Comment by vuongxuongminh** [comment]
Good catch! We should to add new extend method `defaultOutputLength` to set default from config in `VXM\Async\Pool` and override `add` method to support set default output length if not set. Would you like to submit a PR?

**Comment by gmarsano** [comment]
This is a little embarrassing. I'd like to contribute, but I don't think I have enough experience for a PR for now.

**Comment by vuongxuongminh** [comment]
I'll take look this week.

**Comment by vuongxuongminh** [comment]
Hi @gmarsano now you can update your package to 2.1.0 and config `outputLength` via third arg or add default config to configurable file.

**Comment by gmarsano** [comment]
Thank you again. It'll be very useful.
