### ISSUE TITLE
Non-static method 'run' should not be called statically error

### ISSUE THREAD

**Issue by saulob** [vuongxuongminh/laravel-async#21]
I'm unable to execute the first code from the readme, it says that I cannot execute the run method

Check the screenshot above

![image](https://user-images.githubusercontent.com/3660977/128258560-e255835c-0a54-4cd2-b3eb-d701840ba539.png)

I'm using Laravel 8 and PHP 7

**Comment by vuongxuongminh** [comment]
Have you import Async fadecade?

```php
<?php

use Async;
```

**Comment by saulob** [comment]
Yeah, did that, did the publish config, everything. 

And still same error.

**Comment by vuongxuongminh** [comment]
Look like you are using `VXM\Async\Async`, could you show me first few lines of your PHP file?

**Comment by CheeseTastisch** [comment]
Same issue for me.
I included use Async, but it didn't fine the Async class.
Have you found a solution @saulob?

**Comment by saulob** [comment]
Sorry @CheeseTastisch, no luck here. I removed it, stopped using it :(

**Comment by CheeseTastisch** [comment]
Hey @saulob.
For me it worked fine, as i installed the ide-helper package and execute the command `php artisan ide:helper:generate`.
I hope this can fix it for you as well.

**Comment by lukasmedia** [comment]
Any updates on this issue?

**Comment by CheeseTastisch** [comment]
@parsasi @lukasmedia 
As i said in the [answer](https://github.com/vuongxuongminh/laravel-async/issues/21#issuecomment-919996721) before, it's working perfect, if you install ide-helper and run `php artisan ide-helper:generate`.

Than import the Async Trait (not `use VXM\Async\Async` but `use Async`).

**Comment by ramanaptr** [comment]
Hi @vuongxuongminh this is my code already implemented and followed your documentation step by step, but I experienced some errors at code editor.

Are you able to guide me, please? on how to use the function with ```use Async```

Screenshot:
<img width="707" alt="Screen Shot 2022-08-27 at 5 39 28 PM" src="https://user-images.githubusercontent.com/22383326/187024629-5cfd265a-fa95-42c5-a0be-066d28dbbf64.png">

**Comment by vuongxuongminh** [comment]
Use `VXM\Async\AsyncFacade as Async;` instead.
