### ISSUE TITLE
Laravel Async behaving synchronously

### ISSUE THREAD

**Issue by mpalmerjac** [vuongxuongminh/laravel-async#23]
Hello.

I am attempting to use your package on Laravel. However I am encountering issues. It may be that I am misinterpreting the documentation, but I'm not sure.

I am executing an anonymous function which requires a fair bit of time. However, when running it appears if it is being run synchronously and takes the same amount of time as before.

I also tried your code example - the one with the for loop to 20, and it took 20 seconds for the prompt to come back.

My code is quite long but this is a small example
Async::run(function () use ($profile, $formData) { 
     // loads of stuff including API calls to other systems using CURL
};

Shouldn't be running in the background while freeing up the interface?

(I'm using Windows 10 btw)

Thanks for your time :)

Matt Palmer
Software developer
James Anthony Consulting

**Comment by vuongxuongminh** [comment]
Hi @mpalmerjac this package only support Unix system with (PCNTL enabled), btw in your case if you want to send multi http request (async http requests) you can give Guzzle a try, hope this information can help you.
