### ISSUE TITLE
Not working with Laravel Sail

### ISSUE THREAD

**Issue by benfiratkaya** [vuongxuongminh/laravel-async#24]
Hello I'm using Laravel Sail. Because I'm Windows user and laravel-async not working with Windows.

When I send async mail, mail not sending. No problem with sync.

My Code:
```php
use Async;


Async::run(function () use ($email, $token) {
  Mail::to($email)->send(new ForgotPassword($token));
});
```

Also not working:
```php
use Async;


for ($i = 1; $i < 20; $i++) {
  Async::run(function () use ($i) {
    sleep(1);
    
    return $i;
  });
}

dd(implode(', ', Async::wait()));
```
Output: ""

Laravel Version:  8.78
OS: Ubuntu 21
PCNTL Enabled.
```
# php -i | grep pcntl
pcntl support => enabled     
```

No error with:
```php
Async::run(function () {


}, [
  'error' => function (\Exception $e) {
    dd($e);
  }
]);
```

**Comment by vuongxuongminh** [comment]
Please try the latest version and make sure your PHP extensions have POSIX and PCNTL.
