### ISSUE TITLE
why do I see the completely synced result?

### ISSUE THREAD

**Issue by karenrmelikyan** [vuongxuongminh/laravel-async#32]
use Async;

for ($i = 1; $i < 20; $i++)  {
    Async::run(function () use ($i) {
           sleep(1);
           return $i;
     });
 }

var_dump(implode(', ', Async::wait()));

result:  string(65) "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19"

**Comment by vuongxuongminh** [comment]
Please try the latest version and make sure your PHP extensions have POSIX and PCNTL.
