### ISSUE TITLE
its not installing on laravel 5.6, can any other way to install this??

### ISSUE THREAD

**Issue by vishalsharma-jft** [vuongxuongminh/laravel-async#4]
roblem 1
    - Installation request for vxm/laravel-async ^1.1 -> satisfiable by vxm/laravel-async[1.1.0].
    - Conclusion: remove laravel/framework v5.6.28
    - Conclusion: don't install laravel/framework v5.6.28
    - vxm/laravel-async 1.1.0 requires illuminate/support ^5.7 || ^6.0 -> satisfiable by laravel/framework[5.7.x-dev, 5.8.x-dev], illuminate/support[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, 6.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.6.28].
    - Can only install one of: laravel/framework[5.8.x-dev, v5.6.28].
    - don't install illuminate/support 5.7.17|don't install laravel/framework v5.6.28
    - don't install illuminate/support 5.7.18|don't install laravel/framework v5.6.28
    - don't install illuminate/support 5.7.19|don't install laravel/framework v5.6.28
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v5.6.28
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.0|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.1|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.10|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.11|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.15|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.2|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.20|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.21|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.22|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.23|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.26|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.27|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.28|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.3|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.4|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.5|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.6|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.7|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.8|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.7.9|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.0|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.11|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.12|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.14|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.15|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.17|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.18|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.19|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.2|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.20|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.22|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.24|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.27|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.28|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.29|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.3|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.30|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.31|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.32|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.33|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.34|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.35|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.4|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.8|don't install laravel/framework v5.6.28
    - don't install illuminate/support v5.8.9|don't install laravel/framework v5.6.28
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.0.0|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.0.1|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.0.2|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.0.3|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.0.4|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.1.0|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.2.0|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.3.0|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.4.1|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.5.0|don't install laravel/framework v5.6.28
    - don't install illuminate/support v6.5.1|don't install laravel/framework v5.6.28
    - Installation request for laravel/framework == 5.6.28.0 -> satisfiable by laravel/framework[v5.6.28].

**Comment by vuongxuongminh** [comment]
Please upgrade your Laravel version.
