### ISSUE TITLE
laravel-async broken with spatie/async 1.6.0

### ISSUE THREAD

**Issue by prattcmp** [vuongxuongminh/laravel-async#41]
`Declaration of VXM\Async\Runtime\ParentRuntime::createProcess($task, ?int $outputLength = null, ?string $binary = 'php'): Spatie\Async\Process\Runnable must be compatible with Spatie\Async\Runtime\ParentRuntime::createProcess($task, ?int $outputLength = null, ?string $binary = 'php', ?int $max_input_size = 100000): Spatie\Async\Process\Runnable {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Declaration of VXM\\Async\\Runtime\\ParentRuntime::createProcess($task, ?int $outputLength = null, ?string $binary = 'php'): Spatie\\Async\\Process\\Runnable must be compatible with Spatie\\Async\\Runtime\\ParentRuntime::createProcess($task, ?int $outputLength = null, ?string $binary = 'php', ?int $max_input_size = 100000): Spatie\\Async\\Process\\Runnable at /var/www/html/vendor/vxm/laravel-async/src/Runtime/ParentRuntime.php:24)"} []`

**Comment by prattcmp** [comment]
Package dependencies are incorrect. laravel-async is not compatible with spatie/async `1.5^` which includes `1.6`.

**Comment by vuongxuongminh** [comment]
Resolved by #44
