### ISSUE TITLE
Not work with async

### ISSUE THREAD

**Issue by santutu** [vuongxuongminh/laravel-async#5]
![image](https://user-images.githubusercontent.com/28470293/69328695-09a8ba80-0c93-11ea-9bc5-2f2c030585a3.png)

![image](https://user-images.githubusercontent.com/28470293/69328425-92732680-0c92-11ea-9c49-d6a948aa63a1.png)
![image](https://user-images.githubusercontent.com/28470293/69328457-9d2dbb80-0c92-11ea-880e-f72789ad23de.png)

Expect work time is 1second but 2second.
Do you know what do i wrong?

**Comment by hannanstd** [comment]
hi
i had this issue. what is the soloution?

**Comment by vuongxuongminh** [comment]
Hi @hannanstd, Are you have PCNTL extension?, What's your OS?

**Comment by hannanstd** [comment]
@vuongxuongminh 
yes it is enabled.
i use ubuntu 20 and apache2 on localhost, nginx on production server.
[](url)
![1](https://user-images.githubusercontent.com/20492081/97804659-92332780-1c66-11eb-9915-f6b237c27639.png)

**Comment by vuongxuongminh** [comment]
Can you show your running code?

**Comment by hannanstd** [comment]
thanks for your help.
![2](https://user-images.githubusercontent.com/20492081/97805235-22bf3700-1c6a-11eb-914c-c8996f8f1473.png)
![3](https://user-images.githubusercontent.com/20492081/97805277-5dc16a80-1c6a-11eb-91d8-54b5f4fb7508.png)

**Comment by vuongxuongminh** [comment]
You're welcome, How about posix extension? Are you install it?

**Comment by hannanstd** [comment]
i guess the problem.
when is use `php -i | grep pcntl` it shows `support => enabled` , but when is use `extension_loaded('pcntl')` it returns `false`

**Comment by hannanstd** [comment]
the problem was solve by reinstalling pcntl. 
but now the results is `null`.

![20](https://user-images.githubusercontent.com/20492081/97807151-6dde4780-1c74-11eb-9447-bb2a42d43cf0.png)

**Comment by vuongxuongminh** [comment]
Can you share your code? Like above but loop 20?

**Comment by hannanstd** [comment]
yes
![21](https://user-images.githubusercontent.com/20492081/97807849-7d5f8f80-1c78-11eb-9574-44b9b0550a14.png)

**Comment by vuongxuongminh** [comment]
Maybe an exception have been throw, try to run:

```php 
Async::run(function() {


}, [
     'error' => function(\Exception $e) {
        dump($e);
    }
]);
```

If exception throw, please ensure your package version's latest: `composer show vxm/laravel-async`

**Comment by hannanstd** [comment]
yes. i had an error.  the error: `"PHP Warning:  Module 'pcntl' already loaded in Unknown on line 0`

i fixed it and now all things is okey.

i prepared an installation guide for instal PCNTL on ubuntu and hopefull for other users:
https://stackoverflow.com/a/64634134/6937189

thanks alot for yout awesome package.
